apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.wordpress.storageClass }}
  storageClassName: {{ .Values.wordpress.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wordpress.storage }}